import {
  Activity,
  BarChart3,
  Bell,
  BookOpen,
  Bot,
  ClipboardCheck,
  Eye,
  FileText,
  CreditCard,
  Gauge,
  LayoutDashboard,
  LineChart,
  ListChecks,
  FlaskConical,
  Target,
  Scale,
  Settings,
  Shield,
  Wallet,
  Radio,
} from "lucide-react";

export const navItems = [
  { href: "/", label: "Dashboard", icon: LayoutDashboard },
  { href: "/workspace", label: "AI Workspace", icon: Bot },
  { href: "/watchlist", label: "Watchlist", icon: Eye },
  { href: "/market", label: "Market Monitor", icon: LineChart },
  { href: "/proposals", label: "Trade Proposals", icon: FileText },
  { href: "/approvals", label: "Approvals", icon: ClipboardCheck },
  { href: "/positions", label: "Positions", icon: Wallet },
  { href: "/strategy-lab", label: "Strategy Lab", icon: FlaskConical },
  { href: "/manual-levels", label: "Manual Levels", icon: Target },
  { href: "/pre-trade", label: "Pre-Trade", icon: Scale },
  { href: "/journal", label: "Journal", icon: BookOpen },
  { href: "/lessons", label: "Lessons", icon: ListChecks },
  { href: "/analytics", label: "Analytics", icon: BarChart3 },
  { href: "/alerts", label: "Alerts", icon: Bell },
  { href: "/market-watcher", label: "Market Watcher", icon: Eye },
  { href: "/knowledge", label: "Knowledge Base", icon: ListChecks },
  { href: "/risk", label: "Risk Settings", icon: Shield },
  { href: "/exchange", label: "Exchange", icon: Radio },
  { href: "/usage", label: "Usage", icon: Gauge },
  { href: "/billing", label: "Billing", icon: CreditCard },
  { href: "/invitations", label: "Invitations", icon: ClipboardCheck },
  { href: "/audit", label: "Audit", icon: Activity },
  { href: "/settings", label: "Settings", icon: Settings },
] as const;
