import {
  Activity,
  BarChart3,
  BookOpen,
  Bot,
  ClipboardCheck,
  Eye,
  FileText,
  CreditCard,
  Gauge,
  LayoutDashboard,
  LineChart,
  ListChecks,
  Settings,
  Shield,
  Wallet,
} from "lucide-react";

export const navItems = [
  { href: "/", label: "Dashboard", icon: LayoutDashboard },
  { href: "/workspace", label: "AI Workspace", icon: Bot },
  { href: "/watchlist", label: "Watchlist", icon: Eye },
  { href: "/market", label: "Market Monitor", icon: LineChart },
  { href: "/proposals", label: "Trade Proposals", icon: FileText },
  { href: "/approvals", label: "Approvals", icon: ClipboardCheck },
  { href: "/positions", label: "Positions", icon: Wallet },
  { href: "/journal", label: "Journal", icon: BookOpen },
  { href: "/analytics", label: "Analytics", icon: BarChart3 },
  { href: "/knowledge", label: "Knowledge Base", icon: ListChecks },
  { href: "/risk", label: "Risk Settings", icon: Shield },
  { href: "/usage", label: "Usage", icon: Gauge },
  { href: "/billing", label: "Billing", icon: CreditCard },
  { href: "/invitations", label: "Invitations", icon: ClipboardCheck },
  { href: "/audit", label: "Audit", icon: Activity },
  { href: "/settings", label: "Settings", icon: Settings },
] as const;
