import type { PerformanceMetrics, PaperPortfolioResponse } from "@/lib/api/types";

function samplePortfolioBreakdownMetrics(netPnl: string): PerformanceMetrics {
  return {
    trade_count: 2,
    wins: 1,
    losses: 1,
    breakeven: 0,
    win_rate: 0.5,
    net_pnl: netPnl,
    gross_profit: "200",
    gross_loss: "50",
    total_fees: "4",
    total_funding: "0",
    avg_win: "200",
    avg_loss: "50",
    expectancy: "75",
    profit_factor: 4,
    avg_r_multiple: 1,
    max_drawdown: "50",
    max_drawdown_pct: 0.005,
    avg_duration_seconds: 3000,
    violations: 0,
    equity_curve: [],
  };
}

export const samplePortfolio: PaperPortfolioResponse = {
  safety: {
    execution_mode: "paper",
    paper_only: true,
    real_trading_enabled: false,
    disclaimer:
      "Paper-only simulated portfolio. Not investment advice. Does not indicate readiness for real money.",
  },
  account: {
    starting_balance: "10000",
    current_equity: "10450",
    cumulative_realized_pnl: "450",
    unrealized_pnl: "25",
    open_trade_count: 1,
    closed_trade_count: 6,
    as_of: "2026-03-01T12:00:00Z",
    limitations: [],
  },
  metrics: {
    trade_count: 6,
    wins: 4,
    losses: 2,
    breakeven: 0,
    win_rate: 0.6667,
    net_pnl: "450",
    gross_profit: "600",
    gross_loss: "150",
    total_fees: "12",
    total_funding: "0",
    avg_win: "150",
    avg_loss: "75",
    expectancy: "75",
    profit_factor: 4,
    avg_r_multiple: 1.2,
    max_drawdown: "120",
    max_drawdown_pct: 0.012,
    avg_duration_seconds: 3600,
    violations: 0,
    equity_curve: [],
  },
  open_exposure: {
    open_trade_count: 1,
    proposal_flow_count: 1,
    paper_validation_count: 0,
    unrealized_pnl_total: "25",
    notional_exposure: "500",
    limitations: [],
  },
  equity_curve: [
    {
      index: 0,
      timestamp: "2026-02-01T00:00:00Z",
      equity: "10000",
      cumulative_realized_pnl: "0",
      unrealized_pnl: null,
      event: "start",
    },
    {
      index: 1,
      timestamp: "2026-02-15T10:00:00Z",
      equity: "10200",
      cumulative_realized_pnl: "200",
      unrealized_pnl: null,
      event: "trade_close",
    },
    {
      index: 2,
      timestamp: "2026-03-01T12:00:00Z",
      equity: "10450",
      cumulative_realized_pnl: "450",
      unrealized_pnl: "25",
      event: "live",
    },
  ],
  daily_series: [
    {
      date: "2026-02-15",
      starting_equity: "10000",
      ending_equity: "10200",
      daily_pnl: "200",
      daily_drawdown: "0",
      daily_drawdown_pct: 0,
      trades_closed: 2,
    },
    {
      date: "2026-03-01",
      starting_equity: "10200",
      ending_equity: "10450",
      daily_pnl: "250",
      daily_drawdown: "50",
      daily_drawdown_pct: 0.0049,
      trades_closed: 1,
    },
  ],
  breakdowns: {
    by_symbol: [
      {
        key: "BTCUSDT",
        metrics: samplePortfolioBreakdownMetrics("350"),
      },
    ],
    by_setup: [{ key: "breakout", metrics: samplePortfolioBreakdownMetrics("100") }],
    by_timeframe: [{ key: "1h", metrics: samplePortfolioBreakdownMetrics("100") }],
    by_strategy: [{ key: "HTF Pullback", metrics: samplePortfolioBreakdownMetrics("200") }],
    by_source: [{ key: "proposal_flow", metrics: samplePortfolioBreakdownMetrics("450") }],
    by_detector: [{ key: "order_block", metrics: samplePortfolioBreakdownMetrics("150") }],
  },
  trend: {
    label: "improving",
    window_days: 14,
    recent_net_pnl: "250",
    prior_net_pnl: "200",
    rationale: "Recent closed trades net positive versus the prior window.",
  },
  date_range: { start: "2026-02-01", end: "2026-03-01" },
  filters_applied: {
    start_date: null,
    end_date: null,
    source: "all",
    symbol: null,
    setup: null,
    timeframe: null,
    timezone: "UTC",
  },
};
