"""initial schema

Revision ID: 7bad3454d0e4
Revises:
Create Date: 2026-06-01 13:09:21.220309
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "7bad3454d0e4"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "indicator_snapshots",
        sa.Column("symbol", sa.String(length=30), nullable=False),
        sa.Column("timeframe", sa.String(length=8), nullable=False),
        sa.Column("rsi", sa.Float(), nullable=True),
        sa.Column("vwap", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("ema_fast", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("ema_slow", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("macd", sa.Float(), nullable=True),
        sa.Column("macd_signal", sa.Float(), nullable=True),
        sa.Column("atr", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("volatility", sa.Float(), nullable=True),
        sa.Column("funding_rate", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("snapshot_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_indicator_snapshots")),
    )
    with op.batch_alter_table("indicator_snapshots", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_indicator_snapshots_symbol"), ["symbol"], unique=False)

    op.create_table(
        "market_snapshots",
        sa.Column("symbol", sa.String(length=30), nullable=False),
        sa.Column("timeframe", sa.String(length=8), nullable=False),
        sa.Column("open", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("high", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("low", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("close", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("volume", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("funding_rate", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("snapshot_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_market_snapshots")),
    )
    with op.batch_alter_table("market_snapshots", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_market_snapshots_symbol"), ["symbol"], unique=False)

    op.create_table(
        "organizations",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organizations")),
        sa.UniqueConstraint("name", name=op.f("uq_organizations_name")),
    )
    op.create_table(
        "setup_definitions",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column(
            "strategy_id",
            sa.Enum(
                "HTF_TREND_PULLBACK",
                "LIQUIDITY_SWEEP_REVERSAL",
                "COUNTERTREND_SHORT_BUILD",
                "PASSIVE_LEVEL_ORDER",
                "PROFIT_PROTECTION",
                "GREEN_DAY_GUARD",
                "MENTAL_CAPITAL_GUARD",
                name="strategyid",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column(
            "category",
            sa.Enum(
                "TREND",
                "REVERSAL",
                "BREAKOUT",
                "MEAN_REVERSION",
                "FUNDING",
                "PASSIVE",
                "PROTECTION",
                name="setupcategory",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("rules", sa.JSON(), nullable=False),
        sa.Column("filters", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_setup_definitions")),
        sa.UniqueConstraint("name", "version", name="uq_setup_name_version"),
    )
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column(
            "role",
            sa.Enum("ADMIN", "TRADER", "VIEWER", name="userrole", native_enum=False, length=40),
            nullable=False,
        ),
        sa.Column(
            "risk_profile",
            sa.Enum(
                "CONSERVATIVE",
                "MODERATE",
                "AGGRESSIVE",
                name="riskprofile",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_table(
        "audit_logs",
        sa.Column("organization_id", sa.Uuid(), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("actor", sa.String(length=128), nullable=False),
        sa.Column(
            "action",
            sa.Enum(
                "SIGNAL_CREATED",
                "RISK_WARNING",
                "RISK_BLOCK",
                "PROPOSAL_CREATED",
                "APPROVAL_DECISION",
                "PAPER_ORDER_CREATED",
                "POSITION_UPDATE",
                "JOURNAL_ENTRY",
                "KILL_SWITCH",
                "PROVIDER_FAILURE",
                "GUARDRAIL_BLOCK",
                name="auditaction",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("resource_type", sa.String(length=80), nullable=False),
        sa.Column("resource_id", sa.String(length=128), nullable=True),
        sa.Column("before", sa.JSON(), nullable=True),
        sa.Column("after", sa.JSON(), nullable=True),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.Column("event_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_audit_logs_organization_id_organizations"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_audit_logs_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
    )
    op.create_table(
        "daily_risk_states",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("realized_pnl", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("unrealized_pnl", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("daily_loss_limit", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("trade_count", sa.Integer(), nullable=False),
        sa.Column("locked", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_daily_risk_states_organization_id_organizations"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_daily_risk_states_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_daily_risk_states")),
        sa.UniqueConstraint("organization_id", "user_id", "day", name="uq_daily_risk_org_user_day"),
    )
    op.create_table(
        "documents",
        sa.Column("organization_id", sa.Uuid(), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column(
            "source_type",
            sa.Enum(
                "PLAYBOOK",
                "PRD",
                "ARCHITECTURE",
                "RISK_POLICY",
                "STRATEGY_TEMPLATE",
                "TRADE_JOURNAL",
                "REVIEW_NOTE",
                "MISTAKES",
                name="documentsourcetype",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("uri", sa.String(length=1024), nullable=True),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_documents_organization_id_organizations"),
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_documents_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_documents")),
    )
    op.create_table(
        "exchange_accounts",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("exchange", sa.String(length=40), nullable=False),
        sa.Column("api_key_ref", sa.String(length=255), nullable=False),
        sa.Column("has_withdrawal_permission", sa.Boolean(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE",
                "DISABLED",
                "REVOKED",
                name="exchangeaccountstatus",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_exchange_accounts_organization_id_organizations"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_exchange_accounts_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_exchange_accounts")),
    )
    op.create_table(
        "memberships",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "OWNER", "ADMIN", "MEMBER", name="membershiprole", native_enum=False, length=40
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_memberships_organization_id_organizations"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_memberships_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_memberships")),
        sa.UniqueConstraint("user_id", "organization_id", name="uq_membership_user_org"),
    )
    op.create_table(
        "positions",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("symbol", sa.String(length=30), nullable=False),
        sa.Column(
            "direction",
            sa.Enum("LONG", "SHORT", name="tradedirection", native_enum=False, length=40),
            nullable=False,
        ),
        sa.Column("size", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("entry_price", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("leverage", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("stop_loss", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("liquidation_price", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("unrealized_pnl", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("realized_pnl", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "OPEN", "CLOSED", "LIQUIDATED", name="positionstatus", native_enum=False, length=40
            ),
            nullable=False,
        ),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_positions_organization_id_organizations"),
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_positions_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_positions")),
    )
    op.create_table(
        "risk_events",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "rule_triggered",
            sa.Enum(
                "MAX_LEVERAGE",
                "MAX_POSITION_SIZE",
                "MAX_DAILY_LOSS",
                "MAX_WEEKLY_LOSS",
                "NO_STOP_LOSS",
                "UNSUPPORTED_COIN",
                "COUNTERTREND_REDUCED_SIZE",
                "VOLATILE_ALTCOIN_REDUCED_SIZE",
                "EXTREME_FUNDING",
                "LOW_VOLUME",
                "WEEKEND_CONDITION",
                "SLEEP_TEST",
                "OVERTRADING",
                "STRONG_GREEN_DAY",
                "COOLDOWN_AFTER_LOSS",
                "KILL_SWITCH",
                name="riskruleid",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column(
            "severity",
            sa.Enum(
                "INFO",
                "LOW",
                "MEDIUM",
                "HIGH",
                "CRITICAL",
                name="riskseverity",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column(
            "action_taken",
            sa.Enum("ALLOW", "WARN", "BLOCK", name="riskaction", native_enum=False, length=40),
            nullable=False,
        ),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("event_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_risk_events_organization_id_organizations"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_risk_events_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_risk_events")),
    )
    op.create_table(
        "setup_performance",
        sa.Column("setup_id", sa.Uuid(), nullable=False),
        sa.Column("trades", sa.Integer(), nullable=False),
        sa.Column("wins", sa.Integer(), nullable=False),
        sa.Column("losses", sa.Integer(), nullable=False),
        sa.Column("win_rate", sa.Float(), nullable=False),
        sa.Column("expectancy", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("avg_pnl", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("avg_stress", sa.Float(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["setup_id"],
            ["setup_definitions.id"],
            name=op.f("fk_setup_performance_setup_id_setup_definitions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_setup_performance")),
        sa.UniqueConstraint("setup_id", name=op.f("uq_setup_performance_setup_id")),
    )
    op.create_table(
        "strategy_signals",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("setup_id", sa.Uuid(), nullable=True),
        sa.Column(
            "strategy_id",
            sa.Enum(
                "HTF_TREND_PULLBACK",
                "LIQUIDITY_SWEEP_REVERSAL",
                "COUNTERTREND_SHORT_BUILD",
                "PASSIVE_LEVEL_ORDER",
                "PROFIT_PROTECTION",
                "GREEN_DAY_GUARD",
                "MENTAL_CAPITAL_GUARD",
                name="strategyid",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("symbol", sa.String(length=30), nullable=False),
        sa.Column("timeframe", sa.String(length=8), nullable=False),
        sa.Column(
            "direction",
            sa.Enum("LONG", "SHORT", name="tradedirection", native_enum=False, length=40),
            nullable=False,
        ),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("entry_low", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("entry_high", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("invalidation", sa.Text(), nullable=False),
        sa.Column("evidence", sa.JSON(), nullable=False),
        sa.Column("risk_notes", sa.JSON(), nullable=False),
        sa.Column("signal_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_strategy_signals_organization_id_organizations"),
        ),
        sa.ForeignKeyConstraint(
            ["setup_id"],
            ["setup_definitions.id"],
            name=op.f("fk_strategy_signals_setup_id_setup_definitions"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_strategy_signals_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_strategy_signals")),
    )
    op.create_table(
        "usage_events",
        sa.Column("organization_id", sa.Uuid(), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("feature", sa.String(length=80), nullable=False),
        sa.Column("model", sa.String(length=80), nullable=True),
        sa.Column("provider", sa.String(length=80), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("estimated_cost", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("tool_calls", sa.Integer(), nullable=False),
        sa.Column("cache_hit", sa.Boolean(), nullable=False),
        sa.Column("fallback_used", sa.Boolean(), nullable=False),
        sa.Column("latency_ms", sa.Float(), nullable=True),
        sa.Column("event_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_usage_events_organization_id_organizations"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_usage_events_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_usage_events")),
    )
    op.create_table(
        "chunks",
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("token_count", sa.Integer(), nullable=True),
        sa.Column("embedding_ref", sa.String(length=128), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["document_id"], ["documents.id"], name=op.f("fk_chunks_document_id_documents")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chunks")),
        sa.UniqueConstraint("document_id", "ordinal", name="uq_chunk_document_ordinal"),
    )
    op.create_table(
        "trade_proposals",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("signal_id", sa.Uuid(), nullable=True),
        sa.Column(
            "strategy_id",
            sa.Enum(
                "HTF_TREND_PULLBACK",
                "LIQUIDITY_SWEEP_REVERSAL",
                "COUNTERTREND_SHORT_BUILD",
                "PASSIVE_LEVEL_ORDER",
                "PROFIT_PROTECTION",
                "GREEN_DAY_GUARD",
                "MENTAL_CAPITAL_GUARD",
                name="strategyid",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("symbol", sa.String(length=30), nullable=False),
        sa.Column("timeframe", sa.String(length=8), nullable=False),
        sa.Column(
            "direction",
            sa.Enum("LONG", "SHORT", name="tradedirection", native_enum=False, length=40),
            nullable=False,
        ),
        sa.Column("entry_price", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("position_size", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("leverage", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("stop_loss", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("take_profits", sa.JSON(), nullable=False),
        sa.Column("breakeven_trigger", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("runner_enabled", sa.Boolean(), nullable=False),
        sa.Column("runner_notes", sa.Text(), nullable=True),
        sa.Column("invalidation", sa.Text(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column(
            "risk_level",
            sa.Enum(
                "INFO",
                "LOW",
                "MEDIUM",
                "HIGH",
                "CRITICAL",
                name="riskseverity",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "PENDING_APPROVAL",
                "APPROVED",
                "REJECTED",
                "EXPIRED",
                "EXECUTED",
                "CANCELLED",
                name="proposalstatus",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_trade_proposals_organization_id_organizations"),
        ),
        sa.ForeignKeyConstraint(
            ["signal_id"],
            ["strategy_signals.id"],
            name=op.f("fk_trade_proposals_signal_id_strategy_signals"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_trade_proposals_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_trade_proposals")),
    )
    op.create_table(
        "approvals",
        sa.Column("proposal_id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "APPROVED",
                "REJECTED",
                "MODIFIED",
                "PAUSED",
                "CANCELLED",
                "CLOSED",
                "NEEDS_MORE_ANALYSIS",
                name="approvalstatus",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column(
            "proposed_action",
            sa.Enum(
                "APPROVE",
                "REJECT",
                "MODIFY",
                "PAUSE",
                "CANCEL",
                "CLOSE",
                "NEEDS_MORE_ANALYSIS",
                name="approvalaction",
                native_enum=False,
                length=40,
            ),
            nullable=True,
        ),
        sa.Column("modified_fields", sa.JSON(), nullable=True),
        sa.Column(
            "risk_level",
            sa.Enum(
                "INFO",
                "LOW",
                "MEDIUM",
                "HIGH",
                "CRITICAL",
                name="riskseverity",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("approval_reason", sa.Text(), nullable=True),
        sa.Column("audit_event_id", sa.Uuid(), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["audit_event_id"],
            ["audit_logs.id"],
            name=op.f("fk_approvals_audit_event_id_audit_logs"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_approvals_organization_id_organizations"),
        ),
        sa.ForeignKeyConstraint(
            ["proposal_id"],
            ["trade_proposals.id"],
            name=op.f("fk_approvals_proposal_id_trade_proposals"),
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_approvals_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_approvals")),
        sa.UniqueConstraint("proposal_id", name=op.f("uq_approvals_proposal_id")),
    )
    op.create_table(
        "journals",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("symbol", sa.String(length=30), nullable=False),
        sa.Column("timeframe", sa.String(length=8), nullable=False),
        sa.Column(
            "direction",
            sa.Enum("LONG", "SHORT", name="tradedirection", native_enum=False, length=40),
            nullable=False,
        ),
        sa.Column(
            "strategy_id",
            sa.Enum(
                "HTF_TREND_PULLBACK",
                "LIQUIDITY_SWEEP_REVERSAL",
                "COUNTERTREND_SHORT_BUILD",
                "PASSIVE_LEVEL_ORDER",
                "PROFIT_PROTECTION",
                "GREEN_DAY_GUARD",
                "MENTAL_CAPITAL_GUARD",
                name="strategyid",
                native_enum=False,
                length=40,
            ),
            nullable=True,
        ),
        sa.Column("entry_rationale", sa.Text(), nullable=False),
        sa.Column("exit_rationale", sa.Text(), nullable=True),
        sa.Column("emotions", sa.JSON(), nullable=False),
        sa.Column("mistakes", sa.JSON(), nullable=False),
        sa.Column("lessons", sa.Text(), nullable=True),
        sa.Column("improvement_rule", sa.Text(), nullable=True),
        sa.Column(
            "result",
            sa.Enum(
                "WIN", "LOSS", "BREAKEVEN", "OPEN", name="traderesult", native_enum=False, length=40
            ),
            nullable=False,
        ),
        sa.Column("pnl", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("stress_score", sa.Integer(), nullable=True),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("screenshot_refs", sa.JSON(), nullable=False),
        sa.Column("linked_proposal_id", sa.Uuid(), nullable=True),
        sa.Column("linked_position_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["linked_position_id"],
            ["positions.id"],
            name=op.f("fk_journals_linked_position_id_positions"),
        ),
        sa.ForeignKeyConstraint(
            ["linked_proposal_id"],
            ["trade_proposals.id"],
            name=op.f("fk_journals_linked_proposal_id_trade_proposals"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_journals_organization_id_organizations"),
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_journals_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_journals")),
    )
    op.create_table(
        "orders",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("proposal_id", sa.Uuid(), nullable=True),
        sa.Column("approval_id", sa.Uuid(), nullable=True),
        sa.Column(
            "mode",
            sa.Enum(
                "PAPER", "READ_ONLY", "TRADE", name="executionmode", native_enum=False, length=40
            ),
            nullable=False,
        ),
        sa.Column("symbol", sa.String(length=30), nullable=False),
        sa.Column(
            "side",
            sa.Enum("BUY", "SELL", name="orderside", native_enum=False, length=40),
            nullable=False,
        ),
        sa.Column(
            "order_type",
            sa.Enum(
                "MARKET",
                "LIMIT",
                "STOP",
                "STOP_LIMIT",
                "TAKE_PROFIT",
                name="ordertype",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("size", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("price", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "OPEN",
                "PARTIALLY_FILLED",
                "FILLED",
                "CANCELLED",
                "REJECTED",
                name="orderstatus",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("reduce_only", sa.Boolean(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("exchange_order_id", sa.String(length=128), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["approval_id"], ["approvals.id"], name=op.f("fk_orders_approval_id_approvals")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_orders_organization_id_organizations"),
        ),
        sa.ForeignKeyConstraint(
            ["proposal_id"],
            ["trade_proposals.id"],
            name=op.f("fk_orders_proposal_id_trade_proposals"),
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_orders_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_orders")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_orders_idempotency_key")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("orders")
    op.drop_table("journals")
    op.drop_table("approvals")
    op.drop_table("trade_proposals")
    op.drop_table("chunks")
    op.drop_table("usage_events")
    op.drop_table("strategy_signals")
    op.drop_table("setup_performance")
    op.drop_table("risk_events")
    op.drop_table("positions")
    op.drop_table("memberships")
    op.drop_table("exchange_accounts")
    op.drop_table("documents")
    op.drop_table("daily_risk_states")
    op.drop_table("audit_logs")
    op.drop_table("users")
    op.drop_table("setup_definitions")
    op.drop_table("organizations")
    with op.batch_alter_table("market_snapshots", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_market_snapshots_symbol"))

    op.drop_table("market_snapshots")
    with op.batch_alter_table("indicator_snapshots", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_indicator_snapshots_symbol"))

    op.drop_table("indicator_snapshots")
    # ### end Alembic commands ###
