"""account scoped native BloFin activity

Revision ID: a10blofinactivity001
Revises: a9knowledgeoutbox001
Create Date: 2026-10-10 10:00:51.861340
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "a10blofinactivity001"
down_revision: str | None = "a9knowledgeoutbox001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "blofin_activity_accounts",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("environment", sa.String(length=16), nullable=False),
        sa.Column("account_uid", sa.String(length=128), nullable=False),
        sa.Column("credential_binding", sa.String(length=64), nullable=False),
        sa.Column("identity_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("identity_error", sa.String(length=80), nullable=True),
        sa.CheckConstraint(
            "environment = 'demo'",
            name=op.f("ck_blofin_activity_accounts_ck_blofin_activity_account_demo"),
        ),
        sa.CheckConstraint(
            "length(account_uid) > 0",
            name=op.f("ck_blofin_activity_accounts_ck_blofin_activity_account_uid"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_blofin_activity_accounts_organization_id_organizations"),
        ),
        sa.PrimaryKeyConstraint(
            "organization_id",
            "environment",
            "account_uid",
            name=op.f("pk_blofin_activity_accounts"),
        ),
    )
    op.create_table(
        "blofin_activity_cursors",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("environment", sa.String(length=16), nullable=False),
        sa.Column("account_uid", sa.String(length=128), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("window_begin_ms", sa.BigInteger(), nullable=False),
        sa.Column("window_end_ms", sa.BigInteger(), nullable=False),
        sa.Column("native_cursor", sa.String(length=128), nullable=True),
        sa.Column("seen_cursors", sa.JSON(), nullable=False),
        sa.Column("window_complete", sa.Boolean(), nullable=False),
        sa.Column("covered_begin_ms", sa.BigInteger(), nullable=True),
        sa.Column("covered_end_ms", sa.BigInteger(), nullable=True),
        sa.Column("gap_detected", sa.Boolean(), nullable=False),
        sa.Column("last_successful_sync", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error_code", sa.String(length=80), nullable=True),
        sa.Column("next_retry_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "kind IN ('order', 'fill')",
            name=op.f("ck_blofin_activity_cursors_ck_blofin_activity_cursor_kind"),
        ),
        sa.CheckConstraint(
            "window_begin_ms >= 0 AND window_end_ms >= window_begin_ms",
            name=op.f("ck_blofin_activity_cursors_ck_blofin_activity_cursor_window"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "environment", "account_uid"],
            [
                "blofin_activity_accounts.organization_id",
                "blofin_activity_accounts.environment",
                "blofin_activity_accounts.account_uid",
            ],
            name="fk_blofin_activity_cursor_scope",
        ),
        sa.PrimaryKeyConstraint(
            "organization_id",
            "environment",
            "account_uid",
            "kind",
            name=op.f("pk_blofin_activity_cursors"),
        ),
    )
    op.create_table(
        "blofin_activity_facts",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("environment", sa.String(length=16), nullable=False),
        sa.Column("account_uid", sa.String(length=128), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("native_id", sa.String(length=128), nullable=False),
        sa.Column("order_id", sa.String(length=128), nullable=False),
        sa.Column("occurred_at_ms", sa.BigInteger(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("instrument_metadata", sa.JSON(), nullable=True),
        sa.Column("metadata_observed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("first_observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "kind IN ('order', 'fill')",
            name=op.f("ck_blofin_activity_facts_ck_blofin_activity_fact_kind"),
        ),
        sa.CheckConstraint(
            "length(content_hash) = 64",
            name=op.f("ck_blofin_activity_facts_ck_blofin_activity_fact_hash"),
        ),
        sa.CheckConstraint(
            "occurred_at_ms >= 0",
            name=op.f("ck_blofin_activity_facts_ck_blofin_activity_fact_time"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "environment", "account_uid"],
            [
                "blofin_activity_accounts.organization_id",
                "blofin_activity_accounts.environment",
                "blofin_activity_accounts.account_uid",
            ],
            name="fk_blofin_activity_fact_scope",
        ),
        sa.PrimaryKeyConstraint(
            "organization_id",
            "environment",
            "account_uid",
            "kind",
            "native_id",
            name=op.f("pk_blofin_activity_facts"),
        ),
    )
    op.create_index(
        op.f("ix_blofin_activity_facts_occurred_at_ms"),
        "blofin_activity_facts",
        ["occurred_at_ms"],
        unique=False,
    )
    op.create_index(
        op.f("ix_blofin_activity_facts_order_id"),
        "blofin_activity_facts",
        ["order_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_blofin_activity_facts_order_id"), table_name="blofin_activity_facts")
    op.drop_index(
        op.f("ix_blofin_activity_facts_occurred_at_ms"), table_name="blofin_activity_facts"
    )
    op.drop_table("blofin_activity_facts")
    op.drop_table("blofin_activity_cursors")
    op.drop_table("blofin_activity_accounts")
    # ### end Alembic commands ###
