"""bounded TrendPulse research screening

Revision ID: a12trendpulsescreen001
Revises: a11experiments001
Create Date: 2026-10-10 20:23:06.794915
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "a12trendpulsescreen001"
down_revision: str | None = "a11experiments001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "trendpulse_screening_runs",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("experiment_id", sa.Uuid(), nullable=False),
        sa.Column("version_id", sa.Uuid(), nullable=False),
        sa.Column("request_id", sa.Uuid(), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("configuration_hash", sa.String(length=64), nullable=False),
        sa.Column("variant_key", sa.String(length=40), nullable=False),
        sa.Column("strategy_version_id", sa.Uuid(), nullable=False),
        sa.Column("strategy_content_hash", sa.String(length=64), nullable=False),
        sa.Column("trigger_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("acquisition_started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("decision_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("evidence_mode", sa.String(length=20), nullable=False),
        sa.Column("receipt_provenance", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("reason", sa.String(length=100), nullable=False),
        sa.Column("trend_receipts", sa.Integer(), nullable=False),
        sa.Column("entry_receipts", sa.Integer(), nullable=False),
        sa.Column("evidence", sa.JSON(), nullable=False),
        sa.Column("evidence_hash", sa.String(length=64), nullable=False),
        sa.Column("signal", sa.JSON(none_as_null=True), nullable=True),
        sa.Column("signal_id", sa.Uuid(), nullable=True),
        sa.Column("dedupe_key", sa.String(length=64), nullable=True),
        sa.Column("duplicate_of", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "(evidence_mode='public_rest' AND receipt_provenance='live_public_rest') OR (evidence_mode='replay' AND receipt_provenance IN ('recorded_public_receipts','synthetic_fixture'))",
            name=op.f("ck_trendpulse_screening_runs_receipt_provenance"),
        ),
        sa.CheckConstraint(
            "(status = 'qualified_research_signal' AND dedupe_key IS NOT NULL AND signal_id IS NOT NULL AND signal IS NOT NULL AND duplicate_of IS NULL) OR (status = 'duplicate' AND dedupe_key IS NULL AND signal_id IS NOT NULL AND duplicate_of IS NOT NULL AND signal IS NULL) OR (status IN ('unavailable','refused','no_setup') AND dedupe_key IS NULL AND signal_id IS NULL AND duplicate_of IS NULL AND signal IS NULL)",
            name=op.f("ck_trendpulse_screening_runs_signal_status"),
        ),
        sa.CheckConstraint(
            "evidence_mode IN ('public_rest','replay')",
            name=op.f("ck_trendpulse_screening_runs_evidence_mode"),
        ),
        sa.CheckConstraint(
            "status IN ('unavailable','refused','no_setup','qualified_research_signal','duplicate')",
            name=op.f("ck_trendpulse_screening_runs_status"),
        ),
        sa.CheckConstraint(
            "decision_at >= acquisition_started_at",
            name=op.f("ck_trendpulse_screening_runs_decision_time"),
        ),
        sa.CheckConstraint(
            "trend_receipts BETWEEN 0 AND 252 AND entry_receipts BETWEEN 0 AND 62",
            name=op.f("ck_trendpulse_screening_runs_receipt_bounds"),
        ),
        sa.ForeignKeyConstraint(
            ["duplicate_of", "version_id", "organization_id", "user_id"],
            [
                "trendpulse_screening_runs.id",
                "trendpulse_screening_runs.version_id",
                "trendpulse_screening_runs.organization_id",
                "trendpulse_screening_runs.user_id",
            ],
            name=op.f("fk_trendpulse_screening_runs_duplicate_of_trendpulse_screening_runs"),
        ),
        sa.ForeignKeyConstraint(
            ["version_id", "experiment_id", "organization_id", "user_id"],
            [
                "experiment_versions.id",
                "experiment_versions.experiment_id",
                "experiment_versions.organization_id",
                "experiment_versions.user_id",
            ],
            name=op.f("fk_trendpulse_screening_runs_version_id_experiment_versions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_trendpulse_screening_runs")),
        sa.UniqueConstraint(
            "id",
            "version_id",
            "organization_id",
            "user_id",
            name=op.f("uq_trendpulse_screening_runs_id"),
        ),
        sa.UniqueConstraint(
            "organization_id",
            "user_id",
            "request_id",
            name=op.f("uq_trendpulse_screening_runs_organization_id"),
        ),
        sa.UniqueConstraint(
            "version_id",
            "variant_key",
            "dedupe_key",
            name=op.f("uq_trendpulse_screening_runs_version_id"),
        ),
    )
    op.create_index(
        "ix_trendpulse_screening_read",
        "trendpulse_screening_runs",
        ["organization_id", "user_id", "version_id", "decision_at"],
        unique=False,
    )
    if op.get_bind().dialect.name == "postgresql":
        op.execute(
            "CREATE FUNCTION trendpulse_screening_immutable() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'screening_immutable'; END; $$"
        )
        op.execute(
            "CREATE TRIGGER trendpulse_screening_guard BEFORE UPDATE OR DELETE ON trendpulse_screening_runs FOR EACH ROW EXECUTE FUNCTION trendpulse_screening_immutable()"
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if op.get_bind().dialect.name == "postgresql":
        op.execute("DROP TRIGGER trendpulse_screening_guard ON trendpulse_screening_runs")
    op.drop_index("ix_trendpulse_screening_read", table_name="trendpulse_screening_runs")
    op.drop_table("trendpulse_screening_runs")
    if op.get_bind().dialect.name == "postgresql":
        op.execute("DROP FUNCTION trendpulse_screening_immutable()")
    # ### end Alembic commands ###
