"""durable knowledge indexing outbox

Revision ID: a9knowledgeoutbox001
Revises: a8agentcapture001
Create Date: 2026-10-09 22:09:15.659277
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "a9knowledgeoutbox001"
down_revision: str | None = "a8agentcapture001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "knowledge_indexing_jobs",
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("document_version", sa.Integer(), nullable=False),
        sa.Column("source_hash", sa.String(length=64), nullable=True),
        sa.Column("operation", sa.String(length=10), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("claimed_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("claim_token", sa.Uuid(), nullable=True),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "operation IN ('upsert', 'delete')",
            name=op.f("ck_knowledge_indexing_jobs_knowledge_indexing_operation"),
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'processing', 'ready', 'failed', 'superseded')",
            name=op.f("ck_knowledge_indexing_jobs_knowledge_indexing_status"),
        ),
        sa.CheckConstraint(
            "attempts >= 0", name=op.f("ck_knowledge_indexing_jobs_knowledge_indexing_attempts")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_knowledge_indexing_jobs")),
    )
    op.create_index(
        "ix_knowledge_indexing_document",
        "knowledge_indexing_jobs",
        ["document_id", "organization_id", "user_id"],
        unique=False,
    )
    op.create_index(
        "ix_knowledge_indexing_due",
        "knowledge_indexing_jobs",
        ["status", "available_at"],
        unique=False,
    )
    op.add_column("documents", sa.Column("indexing_generation", sa.Uuid(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("documents", "indexing_generation")
    op.drop_index("ix_knowledge_indexing_due", table_name="knowledge_indexing_jobs")
    op.drop_index("ix_knowledge_indexing_document", table_name="knowledge_indexing_jobs")
    op.drop_table("knowledge_indexing_jobs")
    # ### end Alembic commands ###
