import type { WatcherMonitoringSnapshot } from "@/lib/api/types";

const EMPTY_FLAGS = {
  market_watcher_enabled: false,
  watcher_orchestration_enabled: false,
  worker_enabled: false,
  market_watcher_bridge_enabled: false,
  market_watcher_bridge_auto_tick: false,
  telegram_alerts_enabled: false,
  telegram_interaction_enabled: false,
  automatic_telegram_delivery_enabled: false,
};

export function makeWatcherMonitoringSnapshot(
  overrides: Partial<WatcherMonitoringSnapshot> = {},
): WatcherMonitoringSnapshot {
  const base: WatcherMonitoringSnapshot = {
    watcher_status: "STOPPED",
    paper_monitoring_status: "STOPPED",
    reason_code: "watcher_disabled",
    block_reasons: [],
    warnings: ["no_approved_strategies"],
    paper_posture: {
      paper_only: true,
      execution_mode: "paper",
      real_trading_enabled: false,
      kill_switch_blocked: false,
      kill_switch_reason_code: null,
      telegram_enabled: false,
      watcher_config_enabled: false,
      runtime_evidence: false,
    },
    config_flags: { ...EMPTY_FLAGS },
    symbols_monitored: ["BTCUSDT", "ETHUSDT", "SOLUSDT"],
    approved_strategies: [],
    last_scan_at: null,
    last_scan_status: null,
    next_scan_at: null,
    next_scan_basis: null,
    market_freshness: {
      status: "unknown",
      observed_at: null,
      symbol: null,
      data_freshness: null,
      quote_max_age_seconds: 10,
      stale_after_minutes: null,
      legacy_scanner_stale_after_minutes: 60,
      quote_fresh: false,
      trade_stream_fresh: false,
      closed_candle_final: null,
      historical_evidence_valid: null,
      setup_lifetime_expired: null,
      usable_as_current_market_price: false,
      presentation: null,
      availability: null,
    },
    provider_health: [],
    setup_assessments: [],
    scanner_candidates: {
      count: 0,
      conditions: [],
      last_scan_at: null,
      source: "market_watcher_scan",
    },
    canonical_candidates: [],
    leases: [],
    worker: {
      name: "alphatrade-worker",
      worker_enabled: false,
      heartbeat_live: false,
      last_beat_at: null,
      status: null,
      paused: null,
      detail: null,
    },
    recent_errors: [],
    limitations: ["No persisted Watcher scan has run for this organization."],
    generated_at: "2026-09-21T14:00:00.000Z",
    paper_only: true,
  };
  return {
    ...base,
    ...overrides,
    paper_posture: { ...base.paper_posture, ...overrides.paper_posture },
    config_flags: { ...base.config_flags, ...overrides.config_flags },
    market_freshness: { ...base.market_freshness, ...overrides.market_freshness },
    scanner_candidates: { ...base.scanner_candidates, ...overrides.scanner_candidates },
    worker: { ...base.worker, ...overrides.worker },
  };
}
